Insert into group_name values ('regular');
Insert into group_name values ('collector');
Insert into group_name values ('returns');
Insert into group_name values ('ordered_once');
Insert into group_name values ('reviewer');
Insert into group_name values ('compulsive');

Insert into category(id, name) values (0, 'animals');
Insert into category(id, name) values (1, 'beard');
Insert into category(id, name) values (2, 'business');
Insert into category(id, name) values (3, 'cars');
Insert into category(id, name) values (4, 'city');
Insert into category(id, name) values (5, 'flowers');
Insert into category(id, name) values (6, 'food');
Insert into category(id, name) values (7, 'nature');
Insert into category(id, name) values (8, 'people');
Insert into category(id, name) values (9, 'sports');
Insert into category(id, name) values (10, 'tech');
Insert into category(id, name) values (11, 'travel');
Insert into category(id, name) values (12, 'water');
